version: '3.8'

services:
  ti-monitoring-web:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data.hdf5:/app/data.hdf5
      - ./config.yaml:/app/config.yaml
      - ./notifications.json:/app/notifications.json
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  ti-monitoring-cron:
    build: .
    volumes:
      - ./data.hdf5:/app/data.hdf5
      - ./config.yaml:/app/config.yaml
      - ./notifications.json:/app/notifications.json
    environment:
      - PYTHONPATH=/app
    command: python cron.py
    restart: unless-stopped